[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Réglages"
serverStatus = "SERVEURS"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT DES SERVEURS MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NEWS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Recherche des News.."
newsErrorFailedSpan = "Impossible de charger les Nouveautés"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune Nouveauté"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est directement envoyé à Mojang et n'est jamais sauvegardé."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Cancel"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Selectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Selectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Réglages"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mises à jours"
navDone = "Terminé"
tabAccountHeaderText = "Réglages du compte"
tabAccountHeaderDesc = "Ajouter un nouveau compte, ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Réglages de Minecraft"
minecraftTabHeaderDesc = "Options pour le démarrage du jeu"
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au démarrage."
launchDetachedTitle = "Processus de démarrage détaché du Launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché du Launcher, fermer ce dernier fermera aussi le Launcher."
tabModsHeaderText = "Réglages du mod"
tabModsHeaderDesc = "Active ou désactive les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Glisser des mods"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour raffraichir)"
shaderpacks = "Shaders"
shaderpackDesc = "Active ou désactive les shaders. Notez que les shaders ne marcheront fluidement uniquement sur les installations puissantes. Vous pouvez ajouter des packs customs ici."
selectShaderpack = "Sélectionner un shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Changer la configuration de java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximum"
minRAM = "RAM minimum"
memoryDesc = "La RAM minimum recommandées est de 3 Go. Mettre les valeurs minimum et maximum à la même valeur réduit le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Executable Java"
javaExecSelDialogTitle = "Sélectionner l'éxecutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'éxecutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options additionnelles de la JVM"
jvmOptsDesc = "Options to be provided to the JVM at runtime. <em>-Xms</em> and <em>-Xmx</em> should not be included."
launcherTabHeaderText = "Réglages du Launcher"
launcherTabHeaderDesc = "Options pour configurer le Launcher en lui-même."
allowPrereleaseTitle = "Autoriser la mise à jour depuis les pré-release."
allowPrereleaseDesc = "Les pré-release ont du nouveau contenu qui n'a pas été testé ou intégré.<br>Toujours activé si vous utilisez une pré-release."
dataDirectoryTitle = "Répertoire des données"
selectDataDirectory = "Sélectionner un répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales sont enregistrées dans ce répertoire de données.<br>Les captures d'écran et les sauvegardes de monde sont stockés dans le fichier d'instance de la configuration du serveur correspondant."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et les notes de mise à jour pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de mise à jour"
changelog = "Changelog"
noReleaseNotes = "Aucune note de mise à jour"
viewReleaseNotes = "Voir les notes de mise à jour sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du Launcher"
launcherUpdatesHeaderDesc = "Télécharge, installe, et vérifie les mises à jour pour le Launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Modifier les notes de mises à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "SE CONNECTER"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur Invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue pendant la connexion"
desc = "Une erreur inconnue est survenue. Regardez la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur pendant le lancement du jeu"
failureText = "Regardez la console (CTRL + Shift + i) pour plus de détails."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations du système.."
noCompatibleJava = "Non compatible<br>Installation Java non trouvée"
installJavaMessage = "Afin de lancer Minecraft, vous avez besoin d'une installation x64 de Java {major}. Voulez-vous en installer une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur pendant le téléchargement de Java"
javaDownloadFailureText = "Regardez la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer le jeu"
javaRequiredMessage = """Une installation x64 valide de Java {major} est requise pour lancer le jeu.<br><br>Référez-vous à ce guide <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">[Java Management Guide]</a> pour voir les instructions afin d'installer manuellement Java."""
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé n'a pas le bon hash, le fichier est peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Regardez la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur pendant le lancement du jeu"
seeConsoleForDetails = "Regardez la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur pendant la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement du jeu.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Terminé, profitez du jeu !"
checkConsoleForDetails = "Merci de regarder la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Recherche des Nouveautés"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Connexion en cours !"
joined = "Connecté à Elkube !"

[js.overlay]
dismiss = "Rejeter"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "L'authentification Microsoft a échouée. Veuillez réessayez."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "La déconnexion Microsoft a échouée. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné : &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C'est votre dernier compte"
lastAccountWarningMessage = "Afin d'utiliser le Launcher, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après.<br><br>Etes-vous sûr(e) de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr(e)"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Impossible de supprimer<br>le mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas en cours d'utilisation puis réessayez."
failedToggleTitle = "Impossible d'activer/désactiver<br>un ou plusieurs mods."
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné: Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requier Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-release"
stableReleaseTitle = "Mise à jour stable"
releaseNotesFailed = "Echec du chargement des notes de mise à jour."

[js.settings.updates]
newReleaseTitle = "Nouvelle MaJ disponible"
newPreReleaseTitle = "Nouvelle pré-release disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Téléchargement depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le Launcher et executez le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Chercher les MaJ"
checkingForUpdatesButton = "Recherche des MaJ.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion à Microsoft"
errorMessage = "Nous n'avons pas pu vous connecter à votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pu être établie à nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'est disponible. <br><br>L'index de distribution est un fichier essentiel qui fourni les derrières informations du serveur. Le Launcher ne peut pas démarrer sans lui. Vérifiez votre connexion Internet puis relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Impossible de raffraichir la connexion"
failedMessage = "Impossible de raffraichir la connexion pour le compte <strong>{account}</strong>. Merci de choisir un autre compte ou de vous reconnecter."
failedMessageSelectAnotherAccount = "Impossible de raffraichir la connexion pour le compte <strong>{account}</strong>. Merci de vous reconnecter."
loginButton = "Se connecter"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche des MaJ..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Chercher les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "Le service d'authentification n'a pas été trouvé. Merci de signaler ce problème."
accountMigratedTitle = "Erreur pendant la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Réessayez avec l'email du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur pendant la connexion :<br>Informations incorrectes"
invalidCredentialsDesc = "L'email ou le mot de passe fourni est incorrect. Merci de réessayer."
tooManyAttemptsTitle = "Erreur pendant la connexion :<br>Trop d'essais"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte récemment. Merci de réessayer plus tard."
invalidTokenTitle = "Erreur pendant la connexion :<br>Token invalide"
invalidTokenDesc = "Le token d'accès fourni est invalide."
tokenHasProfileTitle = "Erreur pendant la connexion :<br>Le token a un compte"
tokenHasProfileDesc = "Le token d'accès est déjà assigné à un compte. Sélectionner des profils n'a pas encore été implémenté."
credentialsMissingTitle = "Erreur pendant la connexion :<br>Informations de connexion manquantes"
credentialsMissingDesc = "Nom d'utilisateur/mot de passe non fourni ou mot de passe inférieur à 3 caractères."
invalidSaltVersionTitle = "Erreur pendant la connexion :<br>Version du sel invalide"
invalidSaltVersionDesc = "Version du sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Merci de signaler cette erreur."
accountGoneTitle = "Erreur pendant la connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers Microsoft. Merci de vous connecter avec Microsoft."
unreachableTitle = "Erreur pendant la connexion :<br>Serveurd injoignables"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Vérifiez que ces serveurs sont en ligne et que vous êtes connectés à Internet, puis réessayez."
gameNotPurchasedTitle = "Erreur pendant la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte auquel vous essayez de vous connecter n'a pas acheté une copie de Minecraft. Vous devriez acheter le jeu sur <a href=\"https://minecraft.net/\">minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue pendant la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue. Regardez la console pour plus de détails."
